-- Default role permissions for sub_admin (main_admin has full access in application code).
-- Safe to re-run: upserts allowed=1 for listed keys.

SET NAMES utf8mb4;

INSERT INTO admin_role_permissions (role_id, permission_key, allowed)
SELECT r.id, p.permission_key, 1
FROM admin_roles r
JOIN (
  SELECT 'pages.homeListings' AS permission_key
  UNION ALL SELECT 'listings.list'
  UNION ALL SELECT 'listings.show'
  UNION ALL SELECT 'listings.new'
  UNION ALL SELECT 'listings.edit'
  UNION ALL SELECT 'listings.delete'
  UNION ALL SELECT 'listings.duplicate'
  UNION ALL SELECT 'types.list'
  UNION ALL SELECT 'types.show'
  UNION ALL SELECT 'types.new'
  UNION ALL SELECT 'types.edit'
  UNION ALL SELECT 'types.delete'
  UNION ALL SELECT 'promotions.list'
  UNION ALL SELECT 'promotions.show'
  UNION ALL SELECT 'promotions.new'
  UNION ALL SELECT 'promotions.edit'
  UNION ALL SELECT 'promotions.delete'
  UNION ALL SELECT 'listing_gallery_images.list'
  UNION ALL SELECT 'listing_gallery_images.show'
  UNION ALL SELECT 'listing_gallery_images.new'
  UNION ALL SELECT 'listing_gallery_images.edit'
  UNION ALL SELECT 'listing_gallery_images.delete'
  UNION ALL SELECT 'listing_related.list'
  UNION ALL SELECT 'listing_related.show'
  UNION ALL SELECT 'listing_related.new'
  UNION ALL SELECT 'listing_related.edit'
  UNION ALL SELECT 'listing_related.delete'
  UNION ALL SELECT 'casts.list'
  UNION ALL SELECT 'casts.show'
  UNION ALL SELECT 'casts.new'
  UNION ALL SELECT 'casts.edit'
  UNION ALL SELECT 'casts.delete'
  UNION ALL SELECT 'countries.list'
  UNION ALL SELECT 'countries.show'
  UNION ALL SELECT 'countries.new'
  UNION ALL SELECT 'countries.edit'
  UNION ALL SELECT 'countries.delete'
  UNION ALL SELECT 'states.list'
  UNION ALL SELECT 'states.show'
  UNION ALL SELECT 'states.new'
  UNION ALL SELECT 'states.edit'
  UNION ALL SELECT 'states.delete'
  UNION ALL SELECT 'cities.list'
  UNION ALL SELECT 'cities.show'
  UNION ALL SELECT 'cities.new'
  UNION ALL SELECT 'cities.edit'
  UNION ALL SELECT 'cities.delete'
  UNION ALL SELECT 'places.list'
  UNION ALL SELECT 'places.show'
  UNION ALL SELECT 'places.new'
  UNION ALL SELECT 'places.edit'
  UNION ALL SELECT 'places.delete'
  UNION ALL SELECT 'users.list'
  UNION ALL SELECT 'users.show'
  UNION ALL SELECT 'users.new'
  UNION ALL SELECT 'users.edit'
  UNION ALL SELECT 'users.delete'
  UNION ALL SELECT 'comments.list'
  UNION ALL SELECT 'comments.show'
  UNION ALL SELECT 'comments.edit'
  UNION ALL SELECT 'comments.delete'
  UNION ALL SELECT 'ratings.list'
  UNION ALL SELECT 'ratings.show'
  UNION ALL SELECT 'ratings.edit'
  UNION ALL SELECT 'ratings.delete'
  UNION ALL SELECT 'uploads.use'
) AS p
WHERE r.name = 'sub_admin'
ON DUPLICATE KEY UPDATE allowed = VALUES(allowed), updated_at = CURRENT_TIMESTAMP;
